### ISSUE TITLE
服务器223.99.254.250:12601也会2~3秒卡死

### ISSUE THREAD

**Issue by qiudaomao** [zzzzer91/douyu_dm#2]
斗鱼最近不知道怎么搞的，即使发心跳包还是会**两到三秒整**就再也收不到弹幕了。重连再来一次又是一样

**Comment by zzzzer91** [comment]
前几天没看到, 不好意思, 服务器可能过段时间会失效, 你用wireshark抓包看看, 我就是这么得到服务器地址的.
